module.exports =
  icon: 'icons/typekit.svg'
  getNames: ->
    Object.keys families
  getLink: (name) ->
    "https://typekit.com/fonts/#{families[name]}"
  normalizeName: (name) ->
    name.toLowerCase().replace(/( )/g, '-')

# curl -s "https://typekit.com/api/v1/json/libraries/full?per_page=500&page=1" | json -u -o library.families name id
families =
  "Aaux Next": "lgmv"
  "Abigail": "nmpn"
  "Abril Display": "dvwp"
  "Abril Fatface": "lgrs"
  "Abril Text": "gjst"
  "Abril Titling": "phpr"
  "Abril Titling Condensed": "lvlr"
  "Abril Titling Narrow": "tdxy"
  "Abril Titling Semicondensed": "hzms"
  "Acta Display": "jtgy"
  "Acta Poster": "spmb"
  "Acta Poster Swashes": "drlt"
  "Acuta": "zcmv"
  "Adage Script": "dltb"
  "Adaptive Mono": "dhjt"
  "Adelle": "gmsj"
  "Adelle Sans": "jcyh"
  "Adobe Caslon Pro": "hmqz"
  "Adobe Garamond Pro": "tmmf"
  "Adobe Jenson Pro": "flbr"
  "Adobe Jenson Pro Caption": "cpvz"
  "Adobe Jenson Pro Display": "vgdt"
  "Adobe Jenson Pro Subhead": "xybl"
  "Adobe Text Pro": "ffcc"
  "Adonis": "qdyr"
  "Adriane Text": "rhsr"
  "Adrianna": "bbvs"
  "Adrianna Condensed": "xvgd"
  "Adrianna Extended": "cxxc"
  "Adrianna Extended Demibold": "ydjd"
  "Akagi Pro": "txql"
  "Aktiv Grotesk Std": "tscy"
  "Alber New Web": "dqrj"
  "Alegreya": "bjtl"
  "Alegreya SC": "xrsc"
  "Alexa Std": "nztd"
  "Alize": "rphd"
  "Allumi Extended STD": "cxnr"
  "Allumi STD": "qrvl"
  "Alpha Echo": "kvxq"
  "Alphatier Pro": "hjlw"
  "Alta California": "glpn"
  "Alternate Gothic No. 1 D": "fwtm"
  "Alternate Gothic No. 2 D": "rjss"
  "Alternate Gothic No. 3 D": "lbmp"
  "Alverata Informal PE": "zwsf"
  "Alverata Irregular PE": "wtzj"
  "Alverata PE": "nszc"
  "Alwyn New Rounded Web": "byws"
  "Alwyn New Web": "ymqr"
  "Ambroise Firmin STD": "zmms"
  "Ambroise Francois STD ": "lmnc"
  "Ambroise STD": "sskw"
  "Anago": "blrk"
  "Anca": "fkmt"
  "Angie Sans STD": "gxdg"
  "Anisette Petite STD": "nrky"
  "Anisette Petite STD SC": "bfnx"
  "Anivers": "rnhy"
  "Anivers SC": "xqhs"
  "Annabelle": "bdyq"
  "Anonymous Pro": "fbln"
  "Apertura": "wshm"
  "Apertura Condensed": "zkbh"
  "Apolline STD": "hfbt"
  "Apolline STD SC": "vzsq"
  "Aragon": "bqqw"
  "Archetype": "mqsr"
  "Arek": "nlmf"
  "Arimo": "nlwf"
  "Armalite Rifle": "czzb"
  "Arno Pro": "xgpm"
  "Arno Pro Caption": "kdvt"
  "Arno Pro Display": "vbkz"
  "Arno Pro Small Text": "kttz"
  "Arno Pro Subhead": "hwmr"
  "Arvo": "tsyb"
  "AsimovSans": "lwmy"
  "Athelas": "zwkx"
  "Atrament Web": "dfjt"
  "Aurea Ultra": "hmcs"
  "Automate": "djqb"
  "Aviano": "fftt"
  "Aviano Didone": "lyqr"
  "Aviano Flare": "rtjn"
  "Aviano Future": "dknz"
  "Aviano Sans": "vbkn"
  "Aviano Serif": "qnpv"
  "Aviano Slab": "bymb"
  "AW Conqueror Carved": "jgkq"
  "AW Conqueror Carved Four": "zvkc"
  "AW Conqueror Carved One": "mytn"
  "AW Conqueror Carved Three": "dyrm"
  "AW Conqueror Carved Two": "nxfz"
  "AW Conqueror Didot": "wcts"
  "AW Conqueror Inline": "hfcb"
  "AW Conqueror Sans": "lwvg"
  "AW Conqueror Slab": "ynqr"
  "Azo Sans": "lyqy"
  "Azo Sans Uber": "dktb"
  "Bad Dog": "jdgx"
  "Badaboom Pro": "phmy"
  "Baker Signet Web": "fhzy"
  "Ballers Delight": "jkjn"
  "Baltica Web": "nkcn"
  "Baltica Web Extra Condensed": "nmhl"
  "Balzano Std": "cyjw"
  "Banshee Std": "yrtq"
  "Barge": "hrjj"
  "Baroque Text": "ftpz"
  "BattleStation": "vygz"
  "BD Brick": "ksgm"
  "BD Colonius": "xvch"
  "BD Geminis": "clbv"
  "BD Jupiter": "fghq"
  "BD Jupiter Stencil": "gzsg"
  "BD Nippori": "xpbt"
  "BD Plakatbau": "xrhd"
  "BD Retrocentric": "ymsd"
  "BD Viewmaster": "ymvm"
  "BDR A3MIK": "blmf"
  "BDR Mono": "kfdw"
  "Bebas Neue": "nrgs"
  "Bell Centennial Std Address": "nglj"
  "Bell Centennial Std Bold Listing": "tnpd"
  "Bell Centennial Std Name & Number": "zkqy"
  "Bell Centennial Std Sub-Caption": "ljlv"
  "Bello Caps": "cjrb"
  "Bello Pro": "ykqk"
  "Bickham Script Pro": "dpzw"
  "Bigfish": "xbgb"
  "BigSmalls Bold": "wrtz"
  "BigSmalls Regular": "pbkk"
  "Birch Std": "hpcm"
  "Bistro Script Web ": "dxwq"
  "Black Beard": "wdsw"
  "Blackoak Std": "bcnr"
  "Blakely": "lrpq"
  "Blambot Casual": "srfh"
  "Blambot FX Pro": "zsfy"
  "Blambot Pro": "kxqg"
  "Blow Up": "hrbg"
  "Blue Goblet": "shwc"
  "Blue Goblet Alternate One": "hlkz"
  "Bodedo": "rypf"
  "BonvenoCF": "fxvw"
  "Bookman": "trlj"
  "Boston Traffic": "dkyc"
  "Botanika Mono Web": "qssm"
  "Botanika Web": "tfhb"
  "Bouffant": "ppdm"
  "Brandon Grotesque": "yvxn"
  "Bree": "ymzk"
  "Bree Serif": "qnhg"
  "Brevia": "yywq"
  "Brioso Pro": "hvfx"
  "Brioso Pro Caption": "jfyp"
  "Brioso Pro Display": "zgsj"
  "Brioso Pro Poster": "vtbt"
  "Brioso Pro Subhead": "vphz"
  "Brush Script Std": "hgrg"
  "Buena Park": "gckb"
  "Burnaby Stencil": "gjsz"
  "Cabazon": "rdpv"
  "Caflisch Script Pro": "jjvs"
  "Caliban Std": "qnhl"
  "Calluna": "vybr"
  "Calluna Sans": "wgzc"
  "CamingoDos Web": "nyvb"
  "Cantarell": "kydd"
  "Capitolium 2": "zhqq"
  "Carbon": "vsqh"
  "Carbon Fence": "zkns"
  "Carbon Phyber": "qkzx"
  "CarbonType": "ksng"
  "Cardigan": "skrz"
  "Cardo": "cnlb"
  "Carta Marina": "cyvn"
  "Catnip": "lthk"
  "Catwing": "vxbz"
  "Century Old Style Std": "vchr"
  "Chainprinter": "ysdr"
  "Chaloops": "cztv"
  "Chaloops Medium": "lhzp"
  "Chandler 42 ": "byvt"
  "Changeling Neo": "dmwg"
  "Changeling Neo Inline ": "tmbb"
  "Changeling Neo Stencil": "gncv"
  "Chaparral Pro": "hrpf"
  "Chaparral Pro Caption": "vxdv"
  "Chaparral Pro Display": "gwkj"
  "Chaparral Pro Subhead": "gbbm"
  "Charbroiled": "pzjx"
  "Charlemagne Std": "sstt"
  "Chauncy Pro": "qxnj"
  "Chauncy Pro Regular": "fmrw"
  "Chemist": "zqbs"
  "Chemist Rough": "ssfx"
  "Chennai": "rqgy"
  "Chennai Slab": "rjvq"
  "Chinchilla": "rxvl"
  "Chinese Rocks": "pfcv"
  "Chippewa Falls": "wyrn"
  "Chunder": "lbcx"
  "Chunk": "klcb"
  "Clavo": "xjbl"
  "Click Clack": "ctyb"
  "Cody Web": "wjvv"
  "Colaborate": "khwj"
  "Comenia Sans Web": "cyhy"
  "Comic Serif Pro": "mkml"
  "Concave Tuscan": "tdtj"
  "Conceal": "sfdy"
  "Continuo Web": "fscr"
  "Coolvetica": "mhvx"
  "Cooper Black Std": "pbzd"
  "Copal Std Decorated": "mtpx"
  "Copal Std Outline": "dpqp"
  "Copal Std Solid": "jbtg"
  "Coquette": "drjf"
  "Cora": "cklb"
  "Coranto 2": "ktbv"
  "Coranto 2 Headline": "dpvc"
  "Corn Dog": "vkcq"
  "Corner Store": "bwbh"
  "Coronette": "xpjz"
  "Corpulent Web": "rgky"
  "Cosmopolitan": "rdnz"
  "Costa STD": "khmq"
  "Cotton": "rlcc"
  "Cottonwood Std": "pkzg"
  "Courier Prime": "xscx"
  "Courier Std": "jxcp"
  "Cowboyslang": "pkff"
  "Cowboyslang Condensed ": "ccdn"
  "Cowboyslang Expanded": "fdyh"
  "Crete": "hwlb"
  "Crete Rounded": "nngn"
  "Crimson": "gtgg"
  "Cronos Pro": "jqgg"
  "Cronos Pro Caption": "btfg"
  "Cronos Pro Display": "ndrt"
  "Cronos Pro Subhead": "wxwc"
  "Cubano": "wljs"
  "Cubano Sharp": "jmbn"
  "Daniel": "pcvr"
  "Dapifer": "cjdr"
  "DDT": "ndxp"
  "De Walpergen's Pica": "xgfd"
  "De Walpergen's Pica Small Caps": "rbmz"
  "Dederon Sans Web": "xtkx"
  "Dederon Serif Web": "khmh"
  "Default Gothic": "jbqf"
  "DejaRip": "mfjw"
  "DeLittle Chromatic": "vhsn"
  "DeLittle Chromatic Inlay": "xmkq"
  "DeLittle Chromatic Outline": "rvpy"
  "Delve Hand": "ctbh"
  "Depot New Condensed Web": "czrb"
  "Depot New Web": "hrrw"
  "Deva Ideal": "dmnv"
  "Diavlo": "lgsh"
  "Dienstag": "sfst"
  "DIN Condensed Web": "gkhs"
  "Dirtstorm": "ybyg"
  "Dirty Bakers Dozen": "gjtg"
  "Dirty Bakers Dozen Scorch": "mvnl"
  "Dirty Bakers Dozen Spraypaint": "nthj"
  "Divulge": "hwks"
  "Domyouji": "lbnp"
  "Double Pica": "ftkg"
  "Double Pica Small Caps": "stkc"
  "Droid Sans": "gkmg"
  "Droid Sans Mono": "vqgt"
  "Droid Serif": "pcpv"
  "Drunk Cowboy": "zlhj"
  "Dry Cowboy": "dpnz"
  "Duality": "pvyk"
  "Duality Sand": "xkcn"
  "Duality Steel": "lcgx"
  "Dustismo": "lbpc"
  "Edding 780": "gjzc"
  "Edita": "gdvw"
  "Edita Small": "ttzz"
  "Edo": "bbfy"
  "Effra": "kldz"
  "Eigerdals": "gckq"
  "Elina Web": "kxrh"
  "Elina Web Decor": "qvgz"
  "Embryo": "plpq"
  "Embryo Open": "wsfq"
  "English": "kwsg"
  "English Small Caps": "btzs"
  "Escoffier Capitaux": "jgwj"
  "Eskapade": "ykbv"
  "Eskapade Fraktur": "gqyb"
  "Essay Text": "mdxv"
  "Estilo": "ywzt"
  "Estilo Pro": "yzhh"
  "Estilo Script": "kqtj"
  "Ethnocentric": "khgt"
  "Europa": "myvg"
  "Expo Sans Pro": "yfxq"
  "Expo Sans Pro Condensed": "xqnp"
  "Expo Serif Pro": "lclf"
  "Expressway": "fjbr"
  "Fanwood": "fsmy"
  "Faricy New Web": "ytjc"
  "Fatboy": "xyqp"
  "Federico Web": "brnf"
  "Felt Tip Roman": "krvz"
  "Felt Tip Senior": "bcpv"
  "Felt Tip Woman": "xpwg"
  "Fenwick ": "nwpm"
  "Fenwick Outline": "tmqm"
  "Fertigo Pro": "pzyv"
  "Fertigo Pro Script": "twbx"
  "FF Amman Sans Web": "dgkf"
  "FF Amman Serif Web": "lqbw"
  "FF Angie Web Pro": "ngqj"
  "FF Avance Web Pro": "rqjk"
  "FF Basic Gothic SC Web Pro": "vndz"
  "FF Basic Gothic Web Pro": "snqb"
  "FF Brokenscript Web": "sxzw"
  "FF Brokenscript Web Condensed": "gwsq"
  "FF Chambers Sans Web": "zkww"
  "FF Cocon Web Pro": "gzwk"
  "FF Dagny Pro": "rlxq"
  "FF Dax Compact Web Pro": "ffht"
  "FF Dax Web Pro": "dbqg"
  "FF Dax Web Pro Condensed": "xjff"
  "FF Dax Wide Web Pro": "lhlb"
  "FF Duper Pro": "chyy"
  "FF Enzo ": "rwbq"
  "FF Ernestine Web Pro": "lvzh"
  "FF Folk Rough Web": "mbhp"
  "FF Folk Web": "rnjs"
  "FF Ginger Web Pro": "fvmr"
  "FF Good Headline Pro Condensed": "rczt"
  "FF Karbid Slab Web Pro": "qkfw"
  "FF Karbid Text Web Pro": "kqbz"
  "FF Karbid Web Pro": "gqch"
  "FF Kava Pro": "ypyb"
  "FF Mach Web Pro": "zgjf"
  "FF Mach Web Pro Condensed": "ywgw"
  "FF Mach Wide Web Pro": "xxss"
  "FF Market": "fytf"
  "FF Meta SC Web Pro": "wvmz"
  "FF Meta Serif SC Web Pro": "hwxc"
  "FF Meta Serif Web Pro": "rrtc"
  "FF Meta Web Pro": "brwr"
  "FF Meta Web Pro Condensed": "yzqx"
  "FF More Pro": "chdm"
  "FF More Pro Condensed": "qqwp"
  "FF More Pro Wide": "rpsd"
  "FF Netto Web": "rgzb"
  "FF Nuvo SC Web Pro": "fthp"
  "FF Nuvo Web Pro": "njjs"
  "FF Prater Block Web": "sbsp"
  "FF Prater Sans Web": "pjnv"
  "FF Prater Script Web": "thcp"
  "FF Prater Serif Web": "clds"
  "FF Providence Sans Web Pro": "jhyn"
  "FF Providence SC Web Pro": "jgdn"
  "FF Providence Web Pro": "txsc"
  "FF Speak Web": "vgxf"
  "FF Spinoza Pro": "cmfb"
  "FF Tisa Pro": "xwmz"
  "FF Tisa Sans Pro": "lgpw"
  "FF Typestar Web ": "hrsz"
  "FF Utility Web Pro": "glmn"
  "FF Zwo Corr Web Pro": "jpkn"
  "Fira Mono": "jcjz"
  "Fira Sans": "cqwn"
  "Flood Std": "khwz"
  "Flower Power": "qcdv"
  "Flyswim": "jnfl"
  "Foco": "gvpz"
  "Forgotten Futurist Shadow": "mtpz"
  "FP Dancer Pro": "wnsg"
  "FP Head Pro": "ncmr"
  "Fragile Bombers": "gxwh"
  "Fragile Bombers Attack": "nthz"
  "Fragile Bombers Down": "zbcg"
  "Franklin Gothic URW": "fbft"
  "Franklin Gothic URW Compressed": "knmp"
  "Franklin Gothic URW Condensed": "pthz"
  "Franklin Gothic URW Condensed SC": "tlqm"
  "Franklin Gothic URW Extra Compressed": "kxxt"
  "Freight Big Pro": "kqdn"
  "Freight Display Pro": "hsff"
  "Freight Micro Pro": "bzqy"
  "Freight Sans Pro": "bgnv"
  "Freight Text Pro": "lstb"
  "French Canon": "myym"
  "French Canon Small Caps": "bcym"
  "French Clarendon Ornamented": "lwgj"
  "French Octagon": "rmzf"
  "French Roast": "fryd"
  "Fusaka Std": "ltcz"
  "Futura PT": "ftnk"
  "Futura PT Condensed": "jxkf"
  "Galette": "vmnk"
  "Garamond Premier Pro": "lfzn"
  "Garamond Premier Pro Caption": "wwvn"
  "Garamond Premier Pro Display": "msmg"
  "Garamond Premier Pro Subhead": "gclg"
  "Garogier": "jwdn"
  "Garvis Pro": "tgbw"
  "Gesta": "bcnl"
  "Giddyup Std": "gkpx"
  "Givry": "nfvx"
  "Gnuolane": "kddp"
  "Goldenbook": "qjwy"
  "Good Kitty": "rgmk"
  "Good Times": "ctzl"
  "Good Times Bad Times": "hjzq"
  "GoodDog New": "fmpj"
  "Gothic Open Shaded": "gpdz"
  "Goudy Bookletter 1911": "mpmx"
  "Grad": "cpmg"
  "Grad SC OSF": "hhdk"
  "Grafolita Script": "frss"
  "Grandma": "zwzx"
  "Graphite Std": "ggfm"
  "Graphite Std Narrow": "cdps"
  "Graphite Std Wide": "qkbb"
  "Graveblade": "vwhs"
  "Great Primer": "kctm"
  "Great Primer Small Caps": "djsq"
  "Grecian Light Face": "tqrs"
  "Gunplay": "gzdg"
  "Gunplay Damage": "pwsj"
  "Gunplay Spraypaint": "pkzf"
  "Gurkner-Jump": "pgmb"
  "Gyparody": "gqbk"
  "Halogen": "rfyp"
  "Harfang Pro": "hstn"
  "Harvester": "sspf"
  "Hayate": "hkvl"
  "Headlight": "fpgz"
  "Heavy Data": "mdps"
  "Hedley New Web": "mnbw"
  "Hellenic Wide": "dlmy"
  "Helsinki": "vbwb"
  "Hilde Sharp": "zqwt"
  "Hill House": "qrhv"
  "Hit": "prhv"
  "Hobo Std": "ybkv"
  "Hooligan": "rwfv"
  "Hotel Open": "smzx"
  "Hotel Solid": "mjpz"
  "Hoverunit": "ncvs"
  "HWT American Chromatic": "fmzh"
  "HWT American Inset": "pkpf"
  "HWT American Outline": "zwqp"
  "HWT American Solid": "kyzh"
  "HWT American Stars": "frpj"
  "HWT American Stars Bottom": "vmbb"
  "HWT American Stars Top": "zssy"
  "HWT Slab Antique": "tjmn"
  "HWT Slab Columbian": "ncbg"
  "Hydrophilia Iced": "bxgy"
  "Hydrophilia Liquid": "bwvb"
  "Hypatia Sans Pro": "xstc"
  "Immi Five O Five": "thfz"
  "Inconsolata": "gmvz"
  "InterFace": "vbpf"
  "Intruder Alert": "bsnk"
  "Ironwood Std": "zfns"
  "Iskra": "bxgc"
  "JAF Bernina Sans": "pljs"
  "JAF Bernina Sans Compressed": "qmkq"
  "JAF Bernina Sans Condensed": "pqtd"
  "JAF Bernina Sans Narrow": "xtmc"
  "JAF Bernino Sans": "rftw"
  "JAF Bernino Sans Compressed": "ssws"
  "JAF Bernino Sans Condensed": "zccv"
  "JAF Bernino Sans Narrow": "ljvn"
  "JAF Domus Titling": "jwbb"
  "JAF Facit": "ttyp"
  "JAF Herb": "gnbj"
  "JAF Herb Condensed": "lmgn"
  "JAF Lapture": "rvnd"
  "JAF Lapture Caption": "wyzn"
  "JAF Lapture Display": "wtgg"
  "JAF Lapture Subhead": "phtx"
  "JAF Mashine": "vyjt"
  "JAF Mashine Rounded": "mhpd"
  "JAF Peacock": "sfpl"
  "JAF Peacock Alternate": "mfhp"
  "JAF Peacock Deep": "hrwv"
  "JAF Peacock Loop": "nrlg"
  "JAF Peacock Short": "psyw"
  "JAF Peacock Swash": "zcjl"
  "JAF Zalamander": "rvhs"
  "JAF Zalamander Caps": "lpgt"
  "JanaThork-Pro": "xwyz"
  "Jeanne Moderno": "tkym"
  "Jeanne Moderno Geometrique": "vsnr"
  "Jeanne Moderno Titling": "kkbv"
  "Jeanne Moderno Ultra": "rbkz"
  "Jesaya ": "slrd"
  "Jinky": "svth"
  "John Doe": "qkzf"
  "Josefin": "vjys"
  "Jubilat": "cwfk"
  "Junction": "lnlc"
  "Junegull": "whhj"
  "Junegull Beach": "brrp"
  "Juniper Std": "vvkr"
  "Kaffeesatz": "jgfl"
  "Kandal": "zfhn"
  "Kari Display Pro": "jlsc"
  "Kari Pro": "nqnd"
  "Kari Pro Wide": "njhs"
  "Karmina Sans": "brjr"
  "Katarine Web": "jdwz"
  "Kegger Collegiate": "rkyr"
  "Kegger US": "zknw"
  "Kelvingrove": "gbmp"
  "Kepler Std": "ymjx"
  "Kepler Std Caption": "mhkk"
  "Kepler Std Condensed Display": "nxdj"
  "Kepler Std Condensed Subhead": "wltw"
  "Kepler Std Display": "cdgy"
  "Kepler Std Extended": "mqwh"
  "Kepler Std Extended Caption": "ggdn"
  "Kepler Std Extended Display": "qdrh"
  "Kepler Std Extended Subhead": "hpbq"
  "Kepler Std Semicondensed": "jhbv"
  "Kepler Std Semicondensed Caption": "rysz"
  "Kepler Std Semicondensed Display": "hztf"
  "Kepler Std Semicondensed Subhead": "bgrk"
  "Kepler Std Subhead": "ztvt"
  "Know Your Product": "rzkj"
  "Komu A": "mbkv"
  "Komu B": "bfxt"
  "Kremlin Pro Web": "ydmk"
  "Kremlin Pro Web Expanded": "qcqb"
  "Kremlin Pro Web Semi Expanded": "cgdb"
  "Krete": "xmhq"
  "Kulturista Web": "kbrb"
  "Larabiefont": "mlyr"
  "Latienne Pro": "jttz"
  "Lato": "jxfv"
  "Le Havre ": "nwxv"
  "Le Havre Rounded": "mcxm"
  "Le Monde Courrier STD": "tnhw"
  "Le Monde Courrier STD 2": "cvjj"
  "Le Monde Journal STD": "mvgb"
  "Le Monde Sans STD": "rshz"
  "League Gothic": "kmpm"
  "League Gothic Condensed": "wvpq"
  "League Script No. 1": "qbgv"
  "Leander Script Pro": "snrq"
  "Learning Curve": "twry"
  "Learning Curve Dashed ": "qsqs"
  "Legendum": "ztvq"
  "Legitima": "wklw"
  "Leitura News": "zbrg"
  "Letter Gothic Std": "fdxw"
  "Lexia": "jmhq"
  "LFT Etica": "stqs"
  "LFT Etica Display": "vyvm"
  "Liberation Sans": "zsyz"
  "Liberation Serif": "lcny"
  "Ligurino": "ftfj"
  "Ligurino Condensed": "fngw"
  "Lilac Malaria ": "vrtl"
  "Linden Hill": "wpgv"
  "Lint McCree": "bkzg"
  "Liquorstore": "fhrm"
  "Liquorstore 3D": "bkdx"
  "Liquorstore Jazz": "gcsq"
  "Lithos Pro": "ykxr"
  "Livory": "hdtl"
  "Lobster": "zsbz"
  "Lourdes": "qjtn"
  "LTC Bodoni 175": "mrnw"
  "LTC Broadway": "tjlh"
  "LTC Broadway Engraved": "xhsc"
  "LTC Globe Gothic": "xnjh"
  "LTC Goudy Ornate": "qhjd"
  "LTC Hess Monoblack": "lwzs"
  "LTC Squareface": "dczc"
  "LTC Squareface Small Caps": "jgsh"
  "Luminance": "pzyp"
  "Luminance SC": "dtyw"
  "Lush Script": "hjnb"
  "Lust": "blcg"
  "Lust Didone": "bbbl"
  "Lust Display": "qypz"
  "Lust Display Didone": "gdvq"
  "Lust Script": "tcqg"
  "Lust Script Display": "mmlh"
  "Luxi Sans": "spyf"
  "Luxi Serif": "ssny"
  "M+ 1c": "qnch"
  "M+ 1m ": "gmnw"
  "Macha": "jyts"
  "Madawaska": "yqyl"
  "Madrone Std": "lfdr"
  "Magion Web": "wtdk"
  "Magistral Web": "hmpn"
  "Magistral Web Compressed": "xxyj"
  "Magistral Web Condensed": "bjnq"
  "Magneta": "kybj"
  "Mahalia": "bvln"
  "Maiola": "fhks"
  "Martini at Joe's": "drkh"
  "Maryam Alternate": "qxhg"
  "Maryam Regular": "jkrp"
  "Matt B": "hnhv"
  "Meloche": "shjv"
  "Mentone": "lrph"
  "Merriweather": "sqwg"
  "Mesquite Std": "yyxy"
  "Metalista Web": "hxwt"
  "Metallophile Sp8": "sdcj"
  "Mic 32 New Rounded Web": "kzcb"
  "Mic 32 New Web": "qjtc"
  "Milibus": "fdly"
  "Millesime": "jhtl"
  "Minerva Modern": "rrrg"
  "Mingler": "sgww"
  "Minion Pro": "nljb"
  "Minion Pro Caption": "pwvm"
  "Minion Pro Condensed": "bkmb"
  "Minion Pro Condensed Caption": "mnjs"
  "Minion Pro Condensed Display": "clyh"
  "Minion Pro Condensed Subhead": "hzyk"
  "Minion Pro Display": "sjrl"
  "Minion Pro Subhead": "gfww"
  "Minion Std Black": "rclj"
  "Mitigate": "fqpt"
  "Mittwoch": "jlnh"
  "Moby": "vswr"
  "Moby Monospaced": "lcgn"
  "Modesto": "jmcg"
  "Modesto Condensed": "xmgm"
  "Modesto Expanded": "jjrz"
  "Modesto Text": "vhpy"
  "Molengo": "jqzh"
  "Mono45 Headline": "mngr"
  "Montag": "wdyd"
  "Mostra Nuova": "dktt"
  "Mostra Nuova Alt A": "qmbs"
  "Mostra Nuova Alt B": "nwjl"
  "Mostra Nuova Alt C": "nlnb"
  "Mostra Nuova Alt D": "mpbv"
  "Motor": "kckf"
  "Motor Stencil": "fzlg"
  "Mufferaw": "kktq"
  "Muscle Narrow": "blhz"
  "Muscle Wide": "rgxv"
  "Museo": "htrh"
  "Museo Sans": "ycvr"
  "Museo Sans Condensed": "gkws"
  "Museo Sans Rounded": "dtgx"
  "Museo Slab": "llxb"
  "Myriad Pro": "cbym"
  "Myriad Pro Condensed": "vdpz"
  "Myriad Pro Semi Condensed": "ylwn"
  "Myriad Std Sketch": "gbbb"
  "Myriad Std Tilt": "nbfh"
  "Mythos Std": "jlqm"
  "Nagomi": "smxk"
  "Nasalization": "jyzd"
  "Natalya": "vzvw"
  "Natalya Alternate One": "wzgr"
  "Natalya Alternate Two": "rfjn"
  "Neuropol Nova": "hldj"
  "Neuropol X ": "ndvj"
  "Neuzon": "nqth"
  "New Cicle": "vsdw"
  "Newcomen": "fgrc"
  "News Gothic Std": "hytk"
  "Nimbus Sans": "jyxm"
  "Nimbus Sans Condensed": "cbsf"
  "Nimbus Sans Extended": "wkbr"
  "Nobile": "smsp"
  "Nouvelle Vague": "qrmf"
  "Nudista Web": "jvbv"
  "Nueva Std": "rwrc"
  "Nueva Std Condensed": "clsw"
  "Nueva Std Extended": "nfyf"
  "Obliqua": "nzvz"
  "OCR-A Std": "lxjw"
  "OCR-B Std": "fnzm"
  "Octin College": "wxch"
  "Octin Prison": "ryfc"
  "Octin Sports": "tgkh"
  "Octin Spraypaint": "tzky"
  "Octin Stencil": "gndv"
  "Octin Vintage": "sbtf"
  "Octynaz": "bvmm"
  "Old Standard": "hhcn"
  "Olidia": "scnw"
  "Omnes Pro": "mpmb"
  "Open Sans": "jtcj"
  "Open Sans Condensed": "kchh"
  "Orator Std": "xlsx"
  "Orbitron": "rfss"
  "Orgovan Rounded Web": "dmfb"
  "Oxtail": "ltxb"
  "P22 FLLW Eaglefeather": "fqdt"
  "P22 FLLW Eaglefeather Informal": "hkvw"
  "P22 FLLW Eaglefeather Small Caps": "qpch"
  "P22 Franklin Caslon": "vkns"
  "P22 Underground": "xjhh"
  "P22 Underground Petite Caps": "zjlx"
  "P22 Underground Small Caps": "nfvg"
  "Pakenham": "bdyv"
  "Parisine Clair STD": "nyvz"
  "Parisine Plus Clair STD": "ysqf"
  "Parisine Plus Sombre STD": "ffkd"
  "Parisine Plus STD": "gcyw"
  "Parisine Sombre STD": "fwwl"
  "Parisine STD": "yymm"
  "Parkway Hotel": "xdzr"
  "Parkway Motel": "qpvq"
  "Pauline": "zvgp"
  "Peachy Keen": "bkpc"
  "Penna": "gxfz"
  "Penna Connected": "lmfs"
  "Penna Connected Swashes": "xchj"
  "Penna Swashes": "dpld"
  "Pepperwood Std": "tpsr"
  "Pepperwood Std Fill": "tswh"
  "Pepperwood Std Outline": "cxvc"
  "Petala Pro": "mcfg"
  "Petersburg Web": "pvnc"
  "Phoreus Cherokee": "kztt"
  "Pill Gothic 300mg": "hcdx"
  "Pill Gothic 600mg": "sdgb"
  "Pill Gothic 900mg": "zwjh"
  "Pirulen": "rmdm"
  "Poetica Std": "vmhs"
  "Poleno": "lsbt"
  "Pollen": "lhjv"
  "Ponderosa Std": "mvzx"
  "Poplar Std": "fsrs"
  "Poster Clean": "qpkn"
  "Postino Std": "wkmr"
  "Pragmatica Web": "cmzp"
  "Pragmatica Web Condensed": "nddy"
  "Prenton": "snfg"
  "Prenton Condensed": "ljkd"
  "Prenton Display": "hdwk"
  "Prenton Ultra Condensed": "gfll"
  "Presicav": "hvcm"
  "Prestige Elite Std": "lzbb"
  "Printf": "hhgr"
  "Private Sans Web": "qtcz"
  "Prociono": "tpnn"
  "Professor Minty": "yqpt"
  "Proxima Nova": "vcsm"
  "Proxima Nova Alt": "gcgw"
  "Proxima Nova Alt Condensed": "rnlm"
  "Proxima Nova Alt Extra Condensed": "twjk"
  "Proxima Nova Condensed": "mtyl"
  "Proxima Nova Extra Condensed": "wxrb"
  "Proxima Nova SC OSF": "bnsy"
  "Proxima Nova SC OSF Condensed": "vdqp"
  "Proxima Nova SC OSF Extra Condensed": "rmtj"
  "Proxima Nova Soft": "hlkx"
  "PT Sans": "lllr"
  "PT Sans Caption": "dydp"
  "PT Sans Narrow": "rmcr"
  "PT Serif": "xcqq"
  "PT Serif Caption": "wnnk"
  "Pupcat": "crvc"
  "Purista Web": "rjbz"
  "Puritan": "ccqc"
  "Quake Std": "vxzg"
  "Quara Web": "qfcs"
  "Quatro": "hptl"
  "Quatro Slab": "dxzd"
  "Quimby Gubernatorial": "mhfk"
  "Quimby Mayoral": "zlxv"
  "Raleway": "nqdy"
  "Ratio": "yqrc"
  "Ratio Display": "lwyp"
  "Reagan": "fqbp"
  "Reenie Beanie": "fbtr"
  "Refrigerator Deluxe": "snjm"
  "Reklame Script": "ghpm"
  "Report": "qwvc"
  "Report School": "wkdn"
  "RePublic Web": "wkdp"
  "RePublic Web Condensed": "fflc"
  "Restore": "xngk"
  "Rexlia": "mqkk"
  "Rieven Uncial": "fzzs"
  "Rinse": "fyfp"
  "Ronnia": "rtgb"
  "Ronnia Condensed": "hzlv"
  "Rooney Sans Web": "mtpj"
  "Rooney Web": "thfh"
  "Rosario": "dvxw"
  "Rosewood Std": "gkhy"
  "Rosewood Std Fill": "rcrp"
  "Rowdy": "msgp"
  "Roycroft": "nrkw"
  "RTF Alexander Quill": "ngqw"
  "RTF Stern Pro": "rkcc"
  "Rukou": "qqfy"
  "Runda": "xnyr"
  "Sail": "vdwc"
  "Salsbury": "wzyl"
  "Sanvito Pro": "lbxf"
  "Sanvito Pro Caption": "xpjb"
  "Sanvito Pro Display": "rhtz"
  "Sanvito Pro Subhead": "xssy"
  "Sarina": "phnf"
  "Saucy Millionaire": "qvwh"
  "saxMono": "fjsz"
  "Scheme": "fdys"
  "SchoolBook Web": "jvcb"
  "SchoolBook Web Condensed": "hncd"
  "Scrivano": "drdl"
  "Sewn": "rmhl"
  "Share OSF": "jzbt"
  "Share Regular": "vnrl"
  "Share Tech": "tszf"
  "Share TechMono": "ypjx"
  "Sharik Sans": "fdvv"
  "Sharktooth": "vnjx"
  "Shlop": "qcsv"
  "Shlop Shloppy": "ttzn"
  "Shrub": "dldb"
  "Shuriken Std": "vvgc"
  "Signo": "mynw"
  "Silicone ": "kjwl"
  "Silkscreen": "wsxd"
  "Simply Mono": "hkfm"
  "Sirba": "tgbb"
  "Sister Frisky": "wqdz"
  "Sketchnote Square": "krjn"
  "Sketchnote Text": "wmzm"
  "Skippy Sharp": "pynt"
  "Skolar Web": "wbmp"
  "Sneakers Pro": "wxlh"
  "Sneakers Script": "kpdg"
  "Sneakers Script Narrow": "ykmb"
  "Sneakers Script Ultra Wide": "ktgn"
  "Sneakers Script Wide": "kyln"
  "Snicker": "mkrf"
  "Sniglet": "pfsq"
  "Soap": "hjxr"
  "Sofachrome": "cntf"
  "Soleil": "phxy"
  "Sommet": "gyyc"
  "Sommet Rounded": "gqfn"
  "Sommet Slab": "qlvb"
  "Sommet Slab Titling Caps": "kwmd"
  "Sophisto": "nnzs"
  "Sophisto SC": "xhsp"
  "Sorts Mill Goudy": "yrwy"
  "Source Code Pro": "dkxf"
  "Source Han Sans Japanese": "pkbr"
  "Source Han Sans Korean": "hgxz"
  "Source Han Sans Simplified Chinese": "wqtd"
  "Source Han Sans Traditional Chinese": "qhzx"
  "Source Sans Pro": "bhyf"
  "Source Serif Pro": "xlqg"
  "Sovba": "djhf"
  "Steinzeit": "pxyp"
  "Steinzeit Fill In": "dqqv"
  "Stencil Std": "xjpx"
  "Strenuous": "hwfj"
  "Strenuous 3D": "ljdq"
  "Strenuous Cast": "srfm"
  "Strumpf Std Contour": "njgn"
  "Strumpf Std Open": "rpkg"
  "Stud": "qfxd"
  "Subway Berlin SC": "cgzm"
  "Subway Berlin STD": "sfdf"
  "Subway New York SC": "dwkp"
  "Subway New York STD": "cxvn"
  "Subway Paris SC": "fkxh"
  "Subway Paris STD": "zrgx"
  "Sui Generis": "ctts"
  "Sunflower": "whtb"
  "Sunshine": "ldbl"
  "Superclarendon ": "ywrj"
  "Sweater School": "rfcm"
  "Swingdancer": "gmjz"
  "Swister": "mdrb"
  "Swister Regular": "rgnc"
  "Synthemesc": "kyyj"
  "T.26 Carbon": "qqmf"
  "Tablet Gothic": "qxcw"
  "Tablet Gothic Compressed": "lgmp"
  "Tablet Gothic Condensed": "flgm"
  "Tablet Gothic Narrow": "ggqq"
  "Tablet Gothic Semi Condensed": "fsmk"
  "Tablet Gothic Wide": "fgpc"
  "Tachyon": "wkby"
  "Tacitus Pro": "pwwk"
  "Tamarillo": "bmlb"
  "Tandelle ": "qywd"
  "Tangerine": "dwdh"
  "Teeshirt": "bxhq"
  "Teimer Web": "svlp"
  "Tekton Pro": "fkjd"
  "Tekton Pro Condensed": "bsjh"
  "Tekton Pro Extended": "fxtn"
  "Tenby Eight ": "qvsv"
  "Tenby Five": "pxcb"
  "Tenby Four": "xxhj"
  "Tenby Seven": "tcxj"
  "Tenby Six": "kzrf"
  "Tenso": "xxpy"
  "Terfens": "yhln"
  "TewentyFourNinetyOne": "qbct"
  "TextBook New Web": "dxlb"
  "Tight": "yqln"
  "Tilden Sans Light Web": "nkpr"
  "Tinos": "plns"
  "Tondo Signage": "pbbh"
  "Trajan Pro 3": "xwct"
  "Trajan Sans Pro": "zlnd"
  "Transmute": "nchn"
  "Tussilago": "sxxr"
  "Ubuntu": "jhhw"
  "Ubuntu Condensed": "kflc"
  "Ubuntu Mono": "vwkk"
  "Uniwars ": "sbpb"
  "Uppercut Angle": "qpgh"
  "Urbana": "txkp"
  "Usurp": "qdmw"
  "Utopia Std": "qpzx"
  "Utopia Std Caption": "dwvv"
  "Utopia Std Display": "ngmz"
  "Utopia Std Headline": "krcv"
  "Utopia Std Subhead": "vlql"
  "Veer Annabelle": "rkwh"
  "Velino Poster": "tvvb"
  "Vera Sans": "lvrl"
  "Vidange Pro": "mdgg"
  "Vinyl": "zgct"
  "Viva Std": "gbnd"
  "Viva Std Condensed": "qmzx"
  "Viva Std Extra Extended": "xsww"
  "VM74": "zlhl"
  "Vollkorn": "pdhm"
  "Voluta Script Pro": "tyqy"
  "Walnut": "qptp"
  "Warnock Pro": "znjr"
  "Warnock Pro Caption": "xtcp"
  "Warnock Pro Display": "ywcd"
  "Westsac": "nyyg"
  "Willow Std": "rnxx"
  "Wordy Diva": "rvnv"
  "Xenara": "mspk"
  "Youngblood": "rnxf"
  "Zalderdash": "ybkj"
  "Zebrawood Std": "hqpx"
  "Zebrawood Std Fill": "frcg"
  "Zekton": "pdcq"
  "ZsaZsa Galore": "vjpz"
  "Zubilo Web Black": "phcq"
  "Zubilo Web Inline": "qdql"
  "Zubilo Web Lined": "mcwh"
  "Zubilo Web Shadow": "cjqd"
